media:
  input: public/uploads
  output: /uploads

content:
  - name: works
    label: Works
    path: src/content/works
    type: collection
    view:
      fields: [title_en, date, medium_en]
    fields:
      - name: title_en
        label: Title (English)
        type: string
        required: true
      - name: title_de
        label: Titel (Deutsch)
        type: string
        required: true
      - name: description_en
        label: Description (English)
        type: rich-text
        required: false
      - name: description_de
        label: Beschreibung (Deutsch)
        type: rich-text
        required: false
      - name: date
        label: Date / Datum
        type: date
        required: false
      - name: medium_en
        label: Medium (English)
        type: string
      - name: medium_de
        label: Medium (Deutsch)
        type: string
      - name: image
        label: Image / Bild
        type: image


  - name: installations
    label: Installations / Installationen
    path: src/content/installations
    type: collection
    view:
      fields: [title_en, date, location_en]
    fields:
      - name: title_en
        label: Title (English)
        type: string
        required: true
      - name: title_de
        label: Titel (Deutsch)
        type: string
        required: true
      - name: description_en
        label: Description (English)
        type: rich-text
        required: false
      - name: description_de
        label: Beschreibung (Deutsch)
        type: rich-text
        required: false
      - name: date
        label: Date / Datum
        type: date
        required: false
      - name: medium_en
        label: Medium (English)
        type: string
      - name: medium_de
        label: Medium (Deutsch)
        type: string
      - name: image
        label: Image / Bild
        type: image
      - name: location_en
        label: Location (English)
        type: string
      - name: location_de
        label: Location (Deutsch)
        type: string

  - name: bio
    label: Bio
    type: file
    path: src/content/bio/index.md
    fields:
      - name: title_en
        label: Title (English)
        type: string
        required: true
      - name: title_de
        label: Titel (Deutsch)
        type: string
        required: true
      - name: body_de
        label: Bio text (Deutsch)
        type: rich-text
      - name: image
        label: Image / Bild
        type: image

  - name: contact
    label: Contact / Kontakt
    type: file
    path: src/content/contact/index.md
    fields:
      - name: title_en
        label: Title (English)
        type: string
        required: true
      - name: title_de
        label: Titel (Deutsch)
        type: string
        required: true
      - name: email
        label: Email
        type: string
      - name: body_de
        label: Contact text (Deutsch)
        type: rich-text

