media:
  input: public/uploads
  output: /uploads

content:
  - name: works
    label: Works
    path: src/content/works
    type: collection
    view:
      fields: [title, date, medium, size]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: rich-text
        required: false
      - name: date
        label: Date
        type: date
        required: false
      - name: medium
        label: Medium
        type: string
      - name: size
        label: Size
        type: string
      - name: image
        label: Image
        type: image
      - name: draft
        label: Draft
        type: boolean
        default: false

  - name: installations
    label: Installations
    path: src/content/installations
    type: collection
    view:
      fields: [title, date, medium, size]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: rich-text
        required: false
      - name: date
        label: Date
        type: date
        required: false
      - name: medium
        label: Medium
        type: string
      - name: size
        label: Size
        type: string
      - name: image
        label: Image
        type: image
      - name: draft
        label: Draft
        type: boolean
        default: false
